destination: "../public/"

default_lang: "en"
url: "http://example.com"

defaults:
  - { values: {
      layout: "default",
      title: "Default Title",
      description: "Default Description"
  } }

  - { scope: { path: "index.html" }, values: { lang: "en" } }
  - { scope: { path: "en" }, values: { lang: "en" } }
  - { scope: { path: "fr" }, values: { lang: "fr" } }
